### ISSUE TITLE
First back-end roadmap

### ISSUE THREAD

**Issue by GabrielBdeC** [GabrielBdeC/todo-list-services#1]
Minimum needed

- [x] [Database structure](https://dbdiagram.io/d/64b8667702bd1c4a5e5eaa1f)
- [x] Create initial configs
- [x] Structure folder, env file and database connection
- [x] Controller, services and models
